Repository iv-org/invidious, pull requests merged in 2020-10, with the labels that each got.

#1372 Add exponential backoff to refresh_channels
  src/invidious/helpers/jobs.cr
Labels: need-code-review

#1403 Extract RefreshChannelsJob
  src/invidious.cr
  src/invidious/helpers/jobs.cr
  src/invidious/jobs/refresh_channels_job.cr
Labels: need-testing

#1437 more polish
  src/invidious/jobs/bypass_captcha_job.cr
Labels: unfinished
