Repository iv-org/invidious, pull requests merged in 2020-12, with the labels that each got.

#1513 Improve error message 2
  src/invidious.cr
  src/invidious/helpers/errors.cr
Labels: enhancement

#1519 Switch to GitHub Actions for CI
  .github/workflows/ci.yml
  .gitignore
  .travis.yml
  README.md
  shard.lock
Labels: need-code-review

#1544 Fix youtube subscription import
  src/invidious.cr
  src/invidious/views/data_control.ecr
Labels: need-testing

#1552 do not proxy hls livestrem on supported browser
  assets/js/player.js
  src/invidious.cr
  src/invidious/views/components/player.ecr
Labels: need-code-review, need-testing

#1106 Set channel thumbnail as icon for feeds
  src/invidious.cr
Labels: need-code-review, unfinished

#1578 Bump dependencies
  shard.lock
  shard.yml
Labels: in-testing

#1580 Css improvements
  assets/css/default.css
Labels: in-testing

#1572 Add DASH quality preference
  assets/js/player.js
  src/invidious/helpers/helpers.cr
  src/invidious/routes/user_preferences.cr
  src/invidious/users.cr
  src/invidious/videos.cr
  src/invidious/views/preferences.ecr
Labels: in-testing

#1608 Add Subscription Traces
  src/invidious.cr
  src/invidious/channels.cr
  src/invidious/jobs/refresh_channels_job.cr
  src/invidious/jobs/refresh_feeds_job.cr
  src/invidious/jobs/subscribe_to_feeds_job.cr
  src/invidious/routes/login.cr
  src/invidious/users.cr
Labels: in-testing
