Repository iv-org/invidious, pull requests merged in 2020-11, with the labels that each got.

#1449 Fix stale playlist video counting on add/drop (#1448)
  src/invidious.cr
Labels: need-testing

#919 Add Previous/Next page buttons at the top of the page
  src/invidious/views/search.ecr
Labels: need-testing

#1477 Fill empty preference values
  src/invidious/views/preferences.ecr
Labels: need-code-review

#1473 Allow setting a custom anti-CAPTCHA API URL
  src/invidious/helpers/helpers.cr
  src/invidious/jobs/bypass_captcha_job.cr
Labels: need-testing

#1490 fix: ytInitialData parsing with regex
  src/invidious/channels.cr
  src/invidious/helpers/helpers.cr
  src/invidious/videos.cr
Labels: need-testing

#1479 Apply dark theme immediately
  assets/css/darktheme.css
  assets/css/default.css
  assets/css/lighttheme.css
  assets/js/themes.js
  src/invidious/views/embed.ecr
  src/invidious/views/template.ecr
Labels: need-code-review, need-testing

#1498 Add backtraces to errors
  src/invidious.cr
  src/invidious/channels.cr
  src/invidious/comments.cr
  src/invidious/helpers/errors.cr
  src/invidious/helpers/tokens.cr
  src/invidious/mixes.cr
  src/invidious/playlists.cr
  src/invidious/routes/embed/index.cr
  src/invidious/routes/embed/show.cr
  src/invidious/routes/playlists.cr
  src/invidious/routes/watch.cr
Labels: in-testing
