Repository iv-org/invidious, pull requests merged in 2021-04, with the labels that each got.

#1960 Add new YT consent cookie to every request
  src/invidious/helpers/utils.cr
Labels: in-testing

#1922 Fix channels' search API
  spec/helpers_spec.cr
  src/invidious/search.cr
Labels: need-code-review, need-testing

#1929 Fix channels' playlists fetching
  spec/helpers_spec.cr
  src/invidious.cr
  src/invidious/channels.cr
Labels: bounty

#1976 Fix footer position to bottom of page
  assets/css/default.css
  src/invidious/views/template.ecr
Labels: unfinished

#1942 Add multiple video route aliases.
  src/invidious.cr
  src/invidious/routes/watch.cr
Labels: in-testing

#1961 Fix API giving ytimg instead of instance URLs for thumbnails
  src/invidious/videos.cr
Labels: in-testing

#2003 Fix iOS 12.5.2 Layout
  assets/css/default.css
Labels: need-code-review, need-testing

#2011 Preserve url params in video route aliases
  src/invidious/routes/watch.cr
Labels: need-code-review, need-testing

#1977 Change empty home page to search engine like layout
  assets/css/default.css
  assets/css/empty.css
  locales/ar.json
  locales/bn_BD.json
  locales/cs.json
  locales/da.json
  locales/de.json
  locales/el.json
  locales/en-US.json
  locales/eo.json
  locales/es.json
  locales/eu.json
  locales/fa.json
  locales/fi.json
  locales/fr.json
  locales/he.json
  locales/hr.json
  locales/hu-HU.json
  locales/id.json
  locales/is.json
  locales/it.json
  locales/ja.json
  locales/nb-NO.json
  locales/nl.json
  locales/pl.json
  locales/pt-BR.json
  locales/pt-PT.json
  locales/ro.json
  locales/ru.json
  locales/si.json
  locales/sk.json
  locales/sr.json
  locales/sr_Cyrl.json
  locales/sv-SE.json
  locales/tr.json
  locales/uk.json
  locales/zh-CN.json
  locales/zh-TW.json
  src/invidious/helpers/macros.cr
  src/invidious/routes/misc.cr
  src/invidious/views/empty.ecr
  src/invidious/views/preferences.ecr
  src/invidious/views/search_homepage.ecr
  src/invidious/views/template.ecr
Labels: unfinished

#1975 add option to disable quic
  src/invidious.cr
  src/invidious/helpers/helpers.cr
  src/invidious/helpers/utils.cr
Labels: unfinished

#1920 Test & fix locales consistency
  locales/ar.json
  locales/da.json
  locales/de.json
  locales/el.json
  locales/eo.json
  locales/es.json
  locales/fa.json
  locales/fi.json
  locales/fr.json
  locales/hr.json
  locales/id.json
  locales/is.json
  locales/it.json
  locales/ja.json
  locales/nb-NO.json
  locales/nl.json
  locales/pl.json
  locales/pt-BR.json
  locales/pt-PT.json
  locales/ro.json
  locales/ru.json
  locales/sv-SE.json
  locales/tr.json
  locales/uk.json
  locales/zh-CN.json
  locales/zh-TW.json
  spec/locales_spec.cr
  src/invidious.cr
  src/invidious/helpers/i18n.cr
Labels: in-testing
