Repository iv-org/invidious, pull requests merged in 2021-02, with the labels that each got.

#1730 Add link[rel="alternate"] pointing to YouTube version
  src/invidious/views/watch.ecr
Labels: need-code-review

#1715 Use large thumbnail for channels in search
  src/invidious/views/components/item.ecr
Labels: in-testing

#1724 Add issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/enhancement.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: unfinished

#1750 Translations update from Weblate
  locales/fi.json
  locales/he.json
Labels: unfinished

#1807 Massively enhance the README
  README.md
Labels: need-code-review

#1735 iOS audio mode double duration fix
  assets/js/player.js
Labels: need-testing
