Repository iv-org/invidious, pull requests merged in 2021-06, with the labels that each got.

#1985 Improve youtube api calls
  src/invidious/channels.cr
  src/invidious/helpers/youtube_api.cr
  src/invidious/playlists.cr
  src/invidious/search.cr
Labels: in-testing

#2115 Upgrade to crystal 1.0.0
  .github/workflows/ci.yml
  docker/Dockerfile
  shard.lock
  shard.yml
  src/invidious.cr
  src/invidious/helpers/utils.cr
  src/invidious/jobs/bypass_captcha_job.cr
  src/invidious/routes/login.cr
  src/invidious/routes/preferences.cr
  src/invidious/users.cr
Labels: in-testing

#2158 Add 10px margin to top and bottom of hr element
  assets/css/default.css
Labels: need-testing

#1940 Add instance redirects!
  locales/ar.json
  locales/bn_BD.json
  locales/cs.json
  locales/da.json
  locales/de.json
  locales/el.json
  locales/en-US.json
  locales/eo.json
  locales/es.json
  locales/eu.json
  locales/fa.json
  locales/fi.json
  locales/fr.json
  locales/he.json
  locales/hr.json
  locales/hu-HU.json
  locales/id.json
  locales/is.json
  locales/it.json
  locales/ja.json
  locales/nb-NO.json
  locales/nl.json
  locales/pl.json
  locales/pt-BR.json
  locales/pt-PT.json
  locales/ro.json
  locales/ru.json
  locales/si.json
  locales/sk.json
  locales/sr.json
  locales/sr_Cyrl.json
  locales/sv-SE.json
  locales/tr.json
  locales/uk.json
  locales/zh-CN.json
  locales/zh-TW.json
  src/invidious.cr
  src/invidious/helpers/errors.cr
  src/invidious/helpers/helpers.cr
  src/invidious/helpers/utils.cr
  src/invidious/routes/misc.cr
  src/invidious/routes/preferences.cr
  src/invidious/users.cr
  src/invidious/views/channel.ecr
  src/invidious/views/community.ecr
  src/invidious/views/components/item.ecr
  src/invidious/views/error.ecr
  src/invidious/views/playlist.ecr
  src/invidious/views/playlists.ecr
  src/invidious/views/preferences.ecr
  src/invidious/views/search.ecr
  src/invidious/views/watch.ecr
Labels: need-code-review, need-testing

#1043 Display username of currently logged in user
  locales/ar.json
  locales/de.json
  locales/el.json
  locales/en-US.json
  locales/eo.json
  locales/es.json
  locales/fa.json
  locales/fi.json
  locales/fr.json
  locales/he.json
  locales/hr.json
  locales/id.json
  locales/is.json
  locales/it.json
  locales/ja.json
  locales/nb-NO.json
  locales/nl.json
  locales/pl.json
  locales/pt-BR.json
  locales/pt-PT.json
  locales/ro.json
  locales/ru.json
  locales/sv-SE.json
  locales/tr.json
  locales/uk.json
  locales/zh-CN.json
  locales/zh-TW.json
  src/invidious/helpers/helpers.cr
  src/invidious/routes/preferences.cr
  src/invidious/users.cr
  src/invidious/views/preferences.ecr
  src/invidious/views/template.ecr
Labels: need-code-review, need-testing

#2183 update video URL for recaptcha detection
  src/invidious/jobs/bypass_captcha_job.cr
Labels: priority:high

#2204 Pick a random video for bypass captcha
  src/invidious/jobs/bypass_captcha_job.cr
Labels: enhancement, need-testing

#2195 Use youtubei API for trending
  src/invidious/helpers/youtube_api.cr
  src/invidious/trending.cr
Labels: in-testing

#2196 Add bidi support
  assets/css/default.css
  src/invidious/views/channel.ecr
  src/invidious/views/community.ecr
  src/invidious/views/components/item.ecr
  src/invidious/views/playlist.ecr
  src/invidious/views/playlists.ecr
  src/invidious/views/watch.ecr
Labels: in-testing
