Repository iv-org/invidious, pull requests merged in 2021-01, with the labels that each got.

#999 Add audio mode link to items
  src/invidious/views/components/item.ecr
Labels: need-code-review

#1636 Rework logging
  src/invidious.cr
  src/invidious/channels.cr
  src/invidious/helpers/helpers.cr
  src/invidious/helpers/logger.cr
  src/invidious/jobs/bypass_captcha_job.cr
  src/invidious/jobs/refresh_channels_job.cr
  src/invidious/jobs/refresh_feeds_job.cr
  src/invidious/jobs/subscribe_to_feeds_job.cr
  src/invidious/jobs/update_decrypt_function_job.cr
  src/invidious/routes/base_route.cr
  src/invidious/routes/login.cr
  src/invidious/routes/watch.cr
  src/invidious/routing.cr
  src/invidious/users.cr
Labels: in-testing

#1619 do not add local to xhr when in videoplayback
  assets/js/player.js
Labels: in-testing

#1679 Fix DASH playback bug in Safari
  assets/js/player.js
Labels: need-code-review

#1674 Add container CI release
  .github/workflows/container-release.yml
Labels: enhancement

#1696 Translations update from Weblate
  locales/bn_BD.json
  locales/da.json
  locales/de.json
  locales/el.json
  locales/eo.json
  locales/es.json
  locales/fa.json
  locales/fi.json
  locales/fr.json
  locales/hr.json
  locales/id.json
  locales/is.json
  locales/it.json
  locales/ja.json
  locales/nb-NO.json
  locales/nl.json
  locales/pl.json
  locales/pt-BR.json
  locales/pt-PT.json
  locales/sk.json
  locales/sr_Cyrl.json
  locales/sv-SE.json
  locales/tr.json
  locales/zh-CN.json
  locales/zh-TW.json
Labels: need-code-review, unfinished

#1702 Config improvements
  src/invidious.cr
  src/invidious/helpers/errors.cr
  src/invidious/helpers/helpers.cr
  src/invidious/helpers/utils.cr
  src/invidious/jobs/bypass_captcha_job.cr
  src/invidious/jobs/refresh_channels_job.cr
  src/invidious/jobs/refresh_feeds_job.cr
  src/invidious/jobs/statistics_refresh_job.cr
  src/invidious/jobs/subscribe_to_feeds_job.cr
  src/invidious/routes/base_route.cr
  src/invidious/routes/login.cr
  src/invidious/routes/user_preferences.cr
  src/invidious/routing.cr
  src/invidious/views/preferences.ecr
  src/invidious/views/template.ecr
Labels: in-testing

#1712 Bump videojs and fix webworker
  assets/css/video-js.min.css
  assets/js/global.js
  assets/js/video.min.js
  src/invidious.cr
  src/invidious/views/components/player_sources.ecr
Labels: need-testing
