Repository iv-org/invidious, pull requests merged in 2021-08, with the labels that each got.

#2298 Switch routing logic to use modules
  src/invidious/routes/base_route.cr
  src/invidious/routes/channels.cr
  src/invidious/routes/embed.cr
  src/invidious/routes/login.cr
  src/invidious/routes/misc.cr
  src/invidious/routes/playlists.cr
  src/invidious/routes/preferences.cr
  src/invidious/routes/search.cr
  src/invidious/routes/watch.cr
  src/invidious/routing.cr
Labels: need-testing

#2255 switch to innertube API for about channels
  src/invidious.cr
  src/invidious/channels/about.cr
  src/invidious/helpers/helpers.cr
  src/invidious/routes/channels.cr
  src/invidious/search.cr
  src/invidious/videos.cr
Labels: in-testing

#2220 Switch to innertube API for videos
  src/invidious/videos.cr
Labels: in-testing

#2329 Fetch with innertube api when video is unavailable
  src/invidious/helpers/youtube_api.cr
  src/invidious/videos.cr
Labels: in-testing

#2324 Use `athena-negotiation` to detect language through Accept-Language header
  shard.lock
  shard.yml
  src/invidious.cr
  src/invidious/routes/login.cr
Labels: bounty

#2269 Extract feed routes
  src/invidious.cr
  src/invidious/helpers/macros.cr
  src/invidious/routes/feeds.cr
  src/invidious/routes/misc.cr
  src/invidious/routes/playlists.cr
  src/invidious/views/feeds/history.ecr
  src/invidious/views/feeds/playlists.ecr
  src/invidious/views/feeds/popular.ecr
  src/invidious/views/feeds/subscriptions.ecr
  src/invidious/views/feeds/trending.ecr
  src/invidious/views/playlist.ecr
  src/invidious/views/preferences.ecr
Labels: need-testing
