Repository iv-org/invidious, pull requests merged in 2021-03, with the labels that each got.

#1729 Support "Database URL" in addition to existing DB-related parameters
  config/config.example.yml
  src/invidious.cr
  src/invidious/helpers/helpers.cr
  src/invidious/users.cr
Labels: in-testing

#1832 Fix engagement
  src/invidious/videos.cr
Labels: need-code-review

#1837 Enhance search filter UI for JS disabled users
  assets/css/default.css
  assets/js/search.js
  src/invidious/views/search.ecr
Labels: need-code-review

#1901 fix comment replies
  assets/js/handlers.js
  assets/js/watch.js
  src/invidious.cr
  src/invidious/comments.cr
Labels: bounty

#1911 Fix long playlists (100+ videos)
  spec/helpers_spec.cr
  src/invidious/channels.cr
  src/invidious/helpers/youtube_api.cr
  src/invidious/playlists.cr
  src/invidious/routes/playlists.cr
  src/invidious/views/playlist.ecr
Labels: bounty, in-testing

#1927 Add "Watch on Youtube" button next to audio mode Icon.
  src/invidious/views/components/item.ecr
Labels: need-testing
