Repository iv-org/invidious, pull requests merged in 2021-12, with the labels that each got.

#2684 Decode title from download widget
  src/invidious/routes/video_playback.cr
Labels: in-testing

#2683 Fix #2682
  src/invidious/comments.cr
Labels: in-testing, ready

#2659 Fix likes/dislikes
  src/invidious/videos.cr
Labels: in-testing, ready

#2576 Fix locales handling
  locales/en-US.json
  src/invidious.cr
  src/invidious/helpers/errors.cr
  src/invidious/helpers/helpers.cr
  src/invidious/helpers/i18n.cr
  src/invidious/helpers/serialized_yt_data.cr
  src/invidious/routes/api/v1/authenticated.cr
  src/invidious/routes/api/v1/channels.cr
  src/invidious/routes/api/v1/feeds.cr
  src/invidious/routes/api/v1/misc.cr
  src/invidious/routes/api/v1/search.cr
  src/invidious/routes/api/v1/videos.cr
  src/invidious/routes/channels.cr
  src/invidious/routes/embed.cr
  src/invidious/routes/feeds.cr
  src/invidious/routes/login.cr
  src/invidious/routes/misc.cr
  src/invidious/routes/playlists.cr
  src/invidious/routes/preferences.cr
  src/invidious/routes/search.cr
  src/invidious/routes/video_playback.cr
  src/invidious/routes/watch.cr
  src/invidious/videos.cr
  src/invidious/views/components/player.ecr
  src/invidious/views/components/video-context-buttons.ecr
  src/invidious/views/feeds/playlists.ecr
  src/invidious/views/preferences.ecr
  src/invidious/views/template.ecr
  src/invidious/views/watch.ecr
Labels: need-code-review, in-testing

#2692 Translations update from Hosted Weblate
  locales/ar.json
  locales/da.json
  locales/de.json
  locales/en-US.json
  locales/fr.json
  locales/hr.json
  locales/id.json
  locales/nb-NO.json
  locales/nl.json
  locales/sr.json
  locales/sr_Cyrl.json
  locales/tr.json
  locales/zh-CN.json
  locales/zh-TW.json
Labels: blocked

#2538 Retain video time position in video player
  assets/js/player.js
  locales/en-US.json
  src/invidious/config.cr
  src/invidious/routes/preferences.cr
  src/invidious/user/preferences.cr
  src/invidious/videos.cr
  src/invidious/views/preferences.ecr
Labels: blocked, in-testing, bounty, bounty:30$
