Repository iv-org/invidious, pull requests merged in 2021-05, with the labels that each got.

#1953 Update regex expressions to handle unexpected '};'
  src/invidious/helpers/helpers.cr
  src/invidious/videos.cr
Labels: bounty

#2110 Fix the parsing of likes in the comments
  src/invidious/comments.cr
Labels: bounty, in-testing

#2085 Bring protodec to the Invidious organization
  shard.lock
  shard.yml
Labels: need-testing
