Repository iv-org/invidious, pull requests merged in 2021-11, with the labels that each got.

#2471 Fix infinite recursion caused by `to_json` methods
  src/invidious/helpers/helpers.cr
  src/invidious/helpers/serialized_yt_data.cr
  src/invidious/playlists.cr
  src/invidious/routes/api/v1/authenticated.cr
  src/invidious/routes/api/v1/videos.cr
  src/invidious/routes/feeds.cr
  src/invidious/videos.cr
Labels: in-testing

#2364 Add compile-time flag to remove code for QUIC
  src/invidious/config.cr
  src/invidious/routes/images.cr
  src/invidious/routes/login.cr
  src/invidious/yt_backend/connection_pool.cr
  src/invidious/yt_backend/youtube_api.cr
Labels: need-testing, ready

#2444 Only use the /redirect endpoint when automatically redirecting to another instance
  src/invidious/routes/misc.cr
  src/invidious/views/channel.ecr
  src/invidious/views/community.ecr
  src/invidious/views/components/item.ecr
  src/invidious/views/components/video-context-buttons.ecr
  src/invidious/views/playlist.ecr
  src/invidious/views/playlists.ecr
  src/invidious/views/watch.ecr
Labels: in-testing, ready

#2589 Bump Crystal version for CI and Docker to 1.2.2
  .github/workflows/ci.yml
  .github/workflows/container-release.yml
  docker/Dockerfile
Labels: blocked

#2555 Enhance some stuff in the README
  README.md
Labels: ready

#2623 Temporarily fix for #2612
  src/invidious/yt_backend/youtube_api.cr
Labels: in-testing

#2656 extract_video_info: Make sure that the Android player response is valid
  src/invidious/videos.cr
Labels: in-testing
