Repository iv-org/invidious, pull requests merged in 2021-09, with the labels that each got.

#2368 Make building in release mode optional
  .github/workflows/ci.yml
  .github/workflows/container-release.yml
  docker/Dockerfile
  docker/Dockerfile.arm64
Labels: need-testing

#2376 Remove 3gp only from the player
  src/invidious/views/components/player.ecr
Labels: in-testing

#2380 Fix invidious showing yt redirect links
  src/invidious/comments.cr
Labels: unfinished

#2378 Bump dependencies
  shard.lock
  shard.yml
  src/invidious.cr
Labels: in-testing

#2379 Handle equirectangular projections for VR
  assets/js/player.js
  src/invidious/videos.cr
  src/invidious/views/watch.ecr
Labels: need-code-review

#2362 Try not to log search queries
  src/invidious/helpers/logger.cr
Labels: blocked

#2390 Unregister captcha job
  src/invidious.cr
Labels: in-testing
