Repository iv-org/invidious, pull requests merged in 2022-02, with the labels that each got.

#2827 More code cleanup
  scripts/git/pre-commit
  scripts/propagate-new-locale-keys.cr
  src/invidious/channels/about.cr
  src/invidious/channels/channels.cr
  src/invidious/comments.cr
  src/invidious/helpers/errors.cr
  src/invidious/helpers/i18n.cr
  src/invidious/helpers/json_filter.cr
  src/invidious/helpers/static_file_handler.cr
  src/invidious/helpers/tokens.cr
  src/invidious/helpers/utils.cr
  src/invidious/playlists.cr
  src/invidious/routes/api/manifest.cr
  src/invidious/routes/api/v1/authenticated.cr
  src/invidious/routes/api/v1/channels.cr
  src/invidious/routes/api/v1/misc.cr
  src/invidious/routes/api/v1/search.cr
  src/invidious/routes/api/v1/videos.cr
  src/invidious/routes/embed.cr
  src/invidious/routes/feeds.cr
  src/invidious/routes/login.cr
  src/invidious/routes/playlists.cr
  src/invidious/routes/search.cr
  src/invidious/routes/video_playback.cr
  src/invidious/search.cr
  src/invidious/users.cr
  src/invidious/videos.cr
  src/invidious/views/add_playlist_items.ecr
  src/invidious/views/search.ecr
  src/invidious/yt_backend/youtube_api.cr
Labels: in-testing

#2856 Fix related videos
  src/invidious/exceptions.cr
  src/invidious/videos.cr
  src/invidious/views/watch.ecr
  src/invidious/yt_backend/extractors.cr
Labels: in-testing

#2492 Change <input value="..."> encoding to HTML.escape
  src/invidious/views/authorize_token.ecr
  src/invidious/views/change_password.ecr
  src/invidious/views/clear_watch_history.ecr
  src/invidious/views/components/item.ecr
  src/invidious/views/components/subscribe_widget.ecr
  src/invidious/views/create_playlist.ecr
  src/invidious/views/delete_account.ecr
  src/invidious/views/delete_playlist.ecr
  src/invidious/views/edit_playlist.ecr
  src/invidious/views/login.ecr
  src/invidious/views/subscription_manager.ecr
  src/invidious/views/template.ecr
  src/invidious/views/token_manager.ecr
Labels: in-testing, ready

#2890 DB: fix inverted arguments in User.update_password()
  src/invidious/database/users.cr
Labels: in-testing

#2891 video_playback: Check "host" parameter validity
  src/invidious/routes/video_playback.cr
Labels: in-testing

#2871 User code cleaning & fixing
  spec/invidious/user/imports_spec.cr
  src/invidious.cr
  src/invidious/routes/account.cr
  src/invidious/routes/api/v1/authenticated.cr
  src/invidious/routes/login.cr
  src/invidious/routes/preferences.cr
  src/invidious/routes/subscriptions.cr
  src/invidious/routing.cr
  src/invidious/search.cr
  src/invidious/user/captcha.cr
  src/invidious/user/cookies.cr
  src/invidious/user/imports.cr
  src/invidious/user/user.cr
  src/invidious/users.cr
  src/invidious/views/template.ecr
  src/invidious/views/user/authorize_token.ecr
  src/invidious/views/user/change_password.ecr
  src/invidious/views/user/clear_watch_history.ecr
  src/invidious/views/user/data_control.ecr
  src/invidious/views/user/delete_account.ecr
  src/invidious/views/user/login.ecr
  src/invidious/views/user/preferences.ecr
  src/invidious/views/user/subscription_manager.ecr
  src/invidious/views/user/token_manager.ecr
Labels: ready

#2923 Fix captions regex
  src/invidious/routes/api/v1/videos.cr
Labels: in-testing

#2922 Download widget fix
  src/invidious.cr
  src/invidious/frontend/watch_page.cr
  src/invidious/routes/api/v1/videos.cr
  src/invidious/routes/video_playback.cr
  src/invidious/routes/watch.cr
  src/invidious/views/watch.ecr
Labels: need-code-review
