Repository iv-org/invidious, pull requests merged in 2022-01, with the labels that each got.

#2744 fix: null ptr while retaining video time
  assets/js/player.js
  assets/js/themes.js
Labels: in-testing

#2677 Temporarily fix for #2612 (round 2)
  src/invidious/yt_backend/youtube_api.cr
Labels: in-testing

#2685 Database improvements
  src/invidious.cr
  src/invidious/channels/channels.cr
  src/invidious/database/annotations.cr
  src/invidious/database/base.cr
  src/invidious/database/channels.cr
  src/invidious/database/nonces.cr
  src/invidious/database/playlists.cr
  src/invidious/database/sessions.cr
  src/invidious/database/statistics.cr
  src/invidious/database/users.cr
  src/invidious/database/videos.cr
  src/invidious/helpers/handlers.cr
  src/invidious/helpers/helpers.cr
  src/invidious/helpers/tokens.cr
  src/invidious/helpers/utils.cr
  src/invidious/jobs/pull_popular_videos_job.cr
  src/invidious/jobs/refresh_channels_job.cr
  src/invidious/jobs/refresh_feeds_job.cr
  src/invidious/jobs/statistics_refresh_job.cr
  src/invidious/playlists.cr
  src/invidious/routes/api/manifest.cr
  src/invidious/routes/api/v1/authenticated.cr
  src/invidious/routes/api/v1/misc.cr
  src/invidious/routes/api/v1/videos.cr
  src/invidious/routes/embed.cr
  src/invidious/routes/feeds.cr
  src/invidious/routes/login.cr
  src/invidious/routes/playlists.cr
  src/invidious/routes/preferences.cr
  src/invidious/routes/video_playback.cr
  src/invidious/routes/watch.cr
  src/invidious/users.cr
  src/invidious/videos.cr
  src/invidious/views/playlist.ecr
  src/invidious/views/watch.ecr
Labels: in-testing

#2545 Add CSV Subscriptions Import
  spec/invidious/user/imports_spec.cr
  src/invidious.cr
  src/invidious/user/imports.cr
Labels: in-testing, bounty, bounty:20$

#2814 Fix search autofocus
  assets/js/handlers.js
  src/invidious/views/components/search_box.ecr
  src/invidious/views/search_homepage.ecr
  src/invidious/views/template.ecr
Labels: in-testing

#2351 Add FAQ link to readme
  .github/ISSUE_TEMPLATE/bug_report.md
  README.md
  locales/en-US.json
  src/invidious/helpers/errors.cr
Labels: in-testing

#2822 Fix loading reddit comments when there are no threads found
  src/invidious/comments.cr
  src/invidious/routes/api/v1/videos.cr
Labels: in-testing

#2847 rename hls to vhs in the player
  assets/js/player.js
Labels: enhancement
