Repository iv-org/invidious, pull requests merged in 2023-05, with the labels that each got.

#3653 Fix watch history order
  src/invidious/database/users.cr
  src/invidious/routes/watch.cr
  src/invidious/user/imports.cr
Labels: ready

#3737 Channels: Fix index out of bounds error
  src/invidious/comments.cr
Labels: ready

#3759 Allow channel urls to be displayed in video's description
  src/invidious/comments.cr
  src/invidious/helpers/utils.cr
  src/invidious/videos/description.cr
  src/invidious/videos/parser.cr
Labels: ready

#3767 Community: Fix live video + parse playlist attachments
  src/invidious/channels/community.cr
  src/invidious/helpers/serialized_yt_data.cr
  src/invidious/yt_backend/extractors.cr
Labels: ready

#3780 Translations update from Hosted Weblate
  locales/cs.json
  locales/es.json
  locales/ko.json
Labels: ready

#3783 Community: Minor HTML/CSS fixes
  assets/css/default.css
  src/invidious/comments.cr
Labels: ready

#3793 Subscriptions: Fix Nil assertion failed
  src/invidious/channels/channels.cr
Labels: ready

#3595 User: Allow CSV Youtube playlists to be imported
  locales/en-US.json
  src/invidious/routes/preferences.cr
  src/invidious/user/imports.cr
  src/invidious/views/feeds/playlists.ecr
  src/invidious/views/user/data_control.ecr
Labels: ready

#3692 API: Add hashtag endpoint
  src/invidious/routes/api/v1/search.cr
  src/invidious/routing.cr
Labels: type:api, ready, module:hashtags

#3797 Translations update from Hosted Weblate
  locales/ar.json
  locales/cs.json
  locales/de.json
  locales/eo.json
  locales/es.json
  locales/hr.json
  locales/it.json
  locales/ja.json
  locales/pl.json
  locales/pt-BR.json
  locales/tr.json
  locales/uk.json
  locales/zh-CN.json
  locales/zh-TW.json
Labels: ready

#3784 Comments: Cleanup code
  spec/invidious/helpers_spec.cr
  spec/parsers_helper.cr
  spec/spec_helper.cr
  src/invidious.cr
  src/invidious/channels/community.cr
  src/invidious/comments.cr
  src/invidious/comments/content.cr
  src/invidious/comments/links_util.cr
  src/invidious/comments/reddit.cr
  src/invidious/comments/reddit_types.cr
  src/invidious/comments/youtube.cr
  src/invidious/frontend/comments_reddit.cr
  src/invidious/frontend/comments_youtube.cr
  src/invidious/routes/api/v1/videos.cr
  src/invidious/routes/watch.cr
  src/invidious/views/community.ecr
Labels: ready

#3804 Search: Parse playlists when searching a channel
  src/invidious/yt_backend/extractors.cr
Labels: need-testing

#3807 Playlists: Fix duplicated videos across pages
  src/invidious/routes/playlists.cr
Labels: ready

#3825 Utils: Add support for short "x ago" forms
  spec/invidious/utils_spec.cr
  src/invidious/helpers/utils.cr
Labels: ready
