Repository iv-org/invidious, pull requests merged in 2023-03, with the labels that each got.

#3654 Add History API
  src/invidious/routes/api/v1/authenticated.cr
  src/invidious/routing.cr
Labels: ready

#3635 Community: parse reply count and polls
  src/invidious/channels/community.cr
Labels: ready, module:channels

#3636 Comments: Add support for custom emojis + member info
  assets/css/default.css
  locales/en-US.json
  src/invidious/comments.cr
Labels: ready, bounty:refused

#3680 Video page: add song title + remove song license on music videos
  locales/en-US.json
  src/invidious/jsonify/api_v1/video_json.cr
  src/invidious/videos.cr
  src/invidious/videos/music.cr
  src/invidious/videos/parser.cr
  src/invidious/views/watch.ecr
Labels: ready
