Repository iv-org/invidious, pull requests merged in 2024-02, with the labels that each got.

#4423 Fix pubsub feed parsing
  src/invidious/routes/feeds.cr
Labels: need-testing

#4205 API: Add playlist and start time to resolve_url
  src/invidious/routes/api/v1/misc.cr
Labels: ready

#4218 API: Unescape search suggestions
  src/invidious/routes/api/v1/search.cr
Labels: ready

#4276 API: Remove the `fields` parameter
  assets/js/notifications.js
  src/invidious.cr
  src/invidious/helpers/handlers.cr
  src/invidious/helpers/helpers.cr
  src/invidious/helpers/json_filter.cr
Labels: ready

#4278 CSS: Fix thumbnails' aspect ratio to prevent CLS
  assets/css/default.css
Labels: ready

#4320 HTML: Add title to toggle theme icon
  locales/en-US.json
  src/invidious/views/template.ecr
Labels: ready

#4342 HTML: Preserve playlist in "Watch on YouTube" link
  src/invidious/views/watch.ecr
Labels: ready

#4348 API: Fix missing wildcards after login redirect
  src/invidious/helpers/utils.cr
Labels: ready

#4376 Stats: Fix two swapped function names
  src/invidious/database/statistics.cr
  src/invidious/jobs/statistics_refresh_job.cr
Labels: ready

#3869 Extractors: Don't error if AuthorId does not exist
  src/invidious/views/components/item.ecr
  src/invidious/views/watch.ecr
  src/invidious/yt_backend/extractors.cr
Labels: ready

#4383 Remove usage of depends_on
  docker-compose.yml
Labels: ready

#4375 I18n: Fix a typo in Finnish localization
  locales/fi.json
Labels: ready

#4405 CSS: expand #contents width on small screens
  assets/css/default.css
  src/invidious/views/template.ecr
Labels: ready

#4412 Channels: Add support for multi-image community posts
  assets/css/carousel.css
  locales/en-US.json
  src/invidious/frontend/comments_youtube.cr
  src/invidious/helpers/i18n.cr
  src/invidious/views/template.ecr
Labels: ready

#4414 WebVTT::Builder: Add logic to escape special chars
  spec/helpers/vtt/builder_spec.cr
  src/invidious/helpers/webvtt.cr
Labels: ready

#4424 I18n: Add missing translation strings
  locales/en-US.json
  src/invidious/frontend/comments_reddit.cr
Labels: blocked, ready

#4431 API: Add APIHandler back
  src/invidious.cr
  src/invidious/helpers/handlers.cr
Labels: ready
