Repository iv-org/invidious, pull requests merged in 2024-01, with the labels that each got.

#4385 Exempt issues with "exempt-stale" from staling
  .github/workflows/stale.yml
Labels: ready

#4335 Add parameter to disable `force_resolve` in `make_client`
  src/invidious/routes/video_playback.cr
  src/invidious/yt_backend/connection_pool.cr
Labels: need-testing

#4403 fix: prevent censoring of self-harm related search queries
  spec/invidious/search/yt_filters_spec.cr
  src/invidious/search/filters.cr
Labels: in-testing
